import { Order } from './../models/order.model';
const products = '/products';
export enum APP_ROUTES {
  HOME = '/home',
  PRODUCTS = products,
  PRODUCT_DETAILS = products,
  MEN_PERFUME = products + '?category=perfum&gender=male',
  WOMEN_PERFUME = products + '?category=perfum&gender=female',
  SKIN_CARE = products + '?category=skin_care',
  HAIR_CARE = products + '?category=hair_care',
  SignIn = '/login',
  SignUp = '/signup',
  AUTH = '/auth',
  AUTH_LOGIN = '/auth/login',
  AUTH_SIGNUP = '/auth/signup',
  DASHBOARD = '/dashboard',
  PROFILE = '/profile',
  SETTINGS = '/settings',
  SHOP = '/shop',
  BLOGS = '/blogs',
  Cart = '/cart',
  Orders = '/orders',
  About = '/about',
  Contact = '/contact',
  ReturnPolicy = '/return-policy',
  PrivacyPolicy = '/privacy-policy',
  NOT_FOUND = '**',
}
